name: Build All Cores

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  batch_1:
    uses: ./.github/workflows/build-all-1.yml

  batch_2:
    uses: ./.github/workflows/build-all-2.yml
